spring.application.name=SAAI-API

# Token service properties
token.service.username=justus.dicker@element-i-schule.de
token.service.password=Robby24.12.
token.service.url=https://sanialarm.de/api/v2/tokens/login

# Alert service properties
alert.service.url=https://sanialarm.de/api/v2/alerts/

# Info screen service URL
infoscreen.service.url=https://sanialarm.de/api/v2/timetable_events/
