spring.application.name=SAAI-API

# Token service properties
token.service.username=justus.dicker@web.de
token.service.password=Justus123!ABC
token.service.url=https://sanialarm.de/api/v2/tokens/login

# Alert service properties
alert.service.url=https://sanialarm.de/api/v2/alerts/
