spring:
  application:
    name: SAAI-API
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: SAAI
    password: Baum

# Token service properties
token:
  service:
    username: jannik@wayshare.de
    password: YwJjQcTra;-K"`5zg9#(@7}!q
    url: https://sanialarm.de/api/v2/tokens/login

#Passwords
users:
  service:
    password: Baum
    url: https://sanialarm.de/api/v2/users/?include_me=false&exclude_level=SENDER
coolingpacks:
  service:
    password: Sani

#sanialarm API links
alert:
  service:
    url: https://sanialarm.de/api/v2/alerts/
infoscreen:
  service:
    url: https://sanialarm.de/api/v2/timetable_events/
external:
  api:
    url: https://sanialarm.de/api/v2


#https
server:
  port: 9090
  ssl:
    key-store: keystore.p12
    key-store-password: baumbaum
    keyStoreType: PKCS12
    keyAlias: saai
    enabled: false

signal-cli:
  address:
    token: eSI5m+gr5qJwa09GNjopbUhMpvXtJc+NUHQeiqWrUhQ=

---
# local-db:
# - use when running the service on the same host with the db
# - this applies to local development as well as prod deployment
spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    url: jdbc:mysql://localhost:3306/SAAI

---
# prod-db:
# - use when running the service locally and want to connect to the production db
spring:
  config:
    activate:
      on-profile: prod-db
  datasource:
    url: jdbc:mysql://saai.wayshare.de:3306/SAAI

---
# host-db-from-container:
# - use when running the service inside a container and the db outside on the host
# - add the extra host 'host.docker.internal:host-gateway' to the container so that
#   the service has access to the ports exposed by the host
spring:
  config:
    activate:
      on-profile: host-db-from-container
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/SAAI

---
# prod:
# - general settings for production; always activate when deploying to prod
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  ssl:
    enabled: true

token:
  service:
    username: sanialarm@wayshare.de
    password: SanialarmAPISSD-Karlsruhe

#signal Sani Live Ticker Group
signal-cli:
  address:
    token: Iu4Tp0Ze8EA8fhzxq6BCQ8FhEs6SiHU+a0WBL+bpPnA=
