spring.application.name=SAAI-API

# Token service properties
##token.service.username=sanialarm@wayshare.de
##token.service.password=SanialarmAPISSD-Karlsruhe
token.service.username=jannik@wayshare.de
token.service.password=YwJjQcTra;-K"`5zg9#(@7}!q


token.service.url=https://sanialarm.de/api/v2/tokens/login

# Alert service properties
alert.service.url=https://sanialarm.de/api/v2/alerts/

# Info screen service URL
infoscreen.service.url=https://sanialarm.de/api/v2/timetable_events/

<<<<<<< HEAD
#https
server.port = 9090
server.ssl.key-store = keystore.p12
server.ssl.key-store-password = baumbaum
server.ssl.keyStoreType = PKCS12
server.ssl.keyAlias = saai
=======


# set port to 9090
server.port=9090
>>>>>>> 5a1785308892d6dc0ab84d8e142607a7fb1d348a
