name: CI - CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  source:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: "Source / Formatting"
            task: "backend:spotlessCheck --no-daemon"
          - name: "Source / Linting"
            task: "backend:checkstyleAll --no-daemon"

    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Run ${{ matrix.name }}
        run: ./gradlew ${{ matrix.task }} --warning-mode all

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: source
    if: needs.source.result != 'failure'

    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-${{ github.run_number }}
          path: backend/build/

      - name: Test Report
        uses: dorny/test-reporter@v2.1.1
        if: ${{ !cancelled() }}
        with:
          name: JUnit Tests
          path: ${{ github.workspace }}/**/build/test-results/**/TEST-*.xml
          reporter: java-junit

      - name: Add Coverage to Summary
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: Code Coverage
          update-comment: true
          comment-type: summary  # only publish unitTest-coverage to PRs
          fail-emoji: ':apple:'
          pass-emoji: ':green_apple:'

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1.2.0
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: gradle-build-${{ github.run_number }}
          path: 'backend/build'

      - name: Run integration tests
        run: ./gradlew backend:integTest --no-daemon

      - name: Test Report
        uses: dorny/test-reporter@v2.1.1
        if: ${{ !cancelled() }}
        with:
          name: JUnit Tests
          path: ${{ github.workspace }}/**/build/test-results/**/TEST-*.xml
          reporter: java-junit
      - name: Add Coverage to Summary / PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        if: ${{ !cancelled() }}
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: Code Coverage
          update-comment: true
          comment-type: ${{ github.event_name == 'pull_request' && 'both' || 'summary' }}
          fail-emoji: ':apple:'
          pass-emoji: ':green_apple:'
