name: CI - CD

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  checks:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: "Source / Formatting"
            task: "backend:spotlessCheck --no-daemon"
          - name: "Source / Linting"
            task: "backend:checkstyleAll --no-daemon"

    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Run ${{ matrix.name }}
        run: ./gradlew ${{ matrix.task }} --warning-mode all
