name: Build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
    steps:
    - name: Checkout sources
      uses: actions/checkout@v5
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Build with Gradle
      run: ./gradlew build
    - name: Test Report
      uses: dorny/test-reporter@v2.1.1
      if: ${{ !cancelled() }}  # run this step even if a previous step failed
      with:
        name: JUnit Tests
        path: ${{ github.workspace }}/**/build/test-results/**/TEST-*.xml
        reporter: java-junit
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.7.2
      with:
        paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
        title: Code Coverage
        update-comment: true

  integ-test:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
    steps:
    - name: Checkout sources
      uses: actions/checkout@v5
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1.2.0
    - name: Run integration tests
      run: ./gradlew backend:integTest
    - name: Test Report
      uses: dorny/test-reporter@v2.1.1
      if: ${{ !cancelled() }}  # run this step even if a previous step failed
      with:
        name: JUnit Tests
        path: ${{ github.workspace }}/**/build/test-results/**/TEST-*.xml
        reporter: java-junit
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.7.2
      with:
        paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
        title: Code Coverage
        update-comment: true

  deploy-dev:
    needs: [build, integ-test]
    if: ${{ success() && github.ref == 'refs/heads/main' && github.repository == 'The-Bug-Bashers/SAAI' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1.2.0
      - name: Build and publish docker image
        run: ./gradlew backend:bootBuildImage -DdockerUser=${{ github.actor }} -DdockerToken=${{ secrets.GITHUB_TOKEN }} -DdockerTag=${{ github.run.number }} --publishImage
      - name: Deploy to the dev server
        env:
          SANIALARM_USER_NAME: ${{ secrets.SANIALARM_USER_NAME }}
          SANIALARM_USER_PASSWORD: ${{ secrets.SANIALARM_USER_PASSWORD }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          SIGNAL_LIVETICKER_GROUP_ID: ${{ secrets.SIGNAL_LIVETICKER_GROUP_ID }}
        run: echo "would deploy to dev environment"
